# Site settings
title: Anne Drolet and Chris Jeakle's Wedding
description: The website for Chris Jeakle and Anne Drolet's wedding.
baseurl: "/DroletJeakleWedding" # the subpath of your site, e.g. /blog/
url: "http://www.chrisjeakle.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Compilation settings
permalink: pretty
